### Send POST request with json body
POST {{protocol}}{{host}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "account_id": "rkojima0213@gmail.com",
    "password": "password"
}

> {%
    client.test("save access token", function() {
        if (response.status === 200) {
            client.global.set('auth_token', response.body.data.token);
        }
    });
%}
