### Send POST request with json body
POST http://localhost/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "account_id": "rkojima0213@gmail.com",
    "password": "password"
}
