### 図書の登録
POST {{protocol}}{{host}}/api/book/register
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

{
  "libraryCode": "lion_library",
  "title": "はらぺこあおむし",
  "isbn": "978-4033280103",
  "author": "エリック・カール",
  "publisher": ""
}
