### サインアップ（アカウント登録）
POST {{protocol}}{{host}}/api/user/signup
Content-Type: application/json
Accept: application/json

{
    "account_id": "rkojima0213@gmail.com",
    "password": "password",
    "name": "某氏"
}
