name: SpellCheck

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - src/laravel/**
  workflow_dispatch:

jobs:
  spell-check:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ ubuntu-20.04 ]

    defaults:
      run:
        working-directory: ./src/laravel

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: install dependencies
        run: npm ci

      - name: Run spell check
        run: npm run spell-check
